package com.sc.dmh.service.inter;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sc.dmh.beans.CbhsUser;
import com.sc.dmh.beans.CbhsUserExample;









public interface UserServiceI {
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    int countByExample(CbhsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    int deleteByExample(CbhsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    int insert(CbhsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    int insertSelective(CbhsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    List<CbhsUser> selectByExample(CbhsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    CbhsUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CbhsUser record, @Param("example") CbhsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CbhsUser record, @Param("example") CbhsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CbhsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CbhsUser record);
    
}
