package com.sc.dmh.beans;

import java.util.ArrayList;
import java.util.List;

public class CbhsUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    public CbhsUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserXmIsNull() {
            addCriterion("user_xm is null");
            return (Criteria) this;
        }

        public Criteria andUserXmIsNotNull() {
            addCriterion("user_xm is not null");
            return (Criteria) this;
        }

        public Criteria andUserXmEqualTo(String value) {
            addCriterion("user_xm =", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotEqualTo(String value) {
            addCriterion("user_xm <>", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmGreaterThan(String value) {
            addCriterion("user_xm >", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmGreaterThanOrEqualTo(String value) {
            addCriterion("user_xm >=", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmLessThan(String value) {
            addCriterion("user_xm <", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmLessThanOrEqualTo(String value) {
            addCriterion("user_xm <=", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmLike(String value) {
            addCriterion("user_xm like", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotLike(String value) {
            addCriterion("user_xm not like", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmIn(List<String> values) {
            addCriterion("user_xm in", values, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotIn(List<String> values) {
            addCriterion("user_xm not in", values, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmBetween(String value1, String value2) {
            addCriterion("user_xm between", value1, value2, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotBetween(String value1, String value2) {
            addCriterion("user_xm not between", value1, value2, "userXm");
            return (Criteria) this;
        }

        public Criteria andZhimingIdIsNull() {
            addCriterion("zhiming_id is null");
            return (Criteria) this;
        }

        public Criteria andZhimingIdIsNotNull() {
            addCriterion("zhiming_id is not null");
            return (Criteria) this;
        }

        public Criteria andZhimingIdEqualTo(Integer value) {
            addCriterion("zhiming_id =", value, "zhimingId");
            return (Criteria) this;
        }

        public Criteria andZhimingIdNotEqualTo(Integer value) {
            addCriterion("zhiming_id <>", value, "zhimingId");
            return (Criteria) this;
        }

        public Criteria andZhimingIdGreaterThan(Integer value) {
            addCriterion("zhiming_id >", value, "zhimingId");
            return (Criteria) this;
        }

        public Criteria andZhimingIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("zhiming_id >=", value, "zhimingId");
            return (Criteria) this;
        }

        public Criteria andZhimingIdLessThan(Integer value) {
            addCriterion("zhiming_id <", value, "zhimingId");
            return (Criteria) this;
        }

        public Criteria andZhimingIdLessThanOrEqualTo(Integer value) {
            addCriterion("zhiming_id <=", value, "zhimingId");
            return (Criteria) this;
        }

        public Criteria andZhimingIdIn(List<Integer> values) {
            addCriterion("zhiming_id in", values, "zhimingId");
            return (Criteria) this;
        }

        public Criteria andZhimingIdNotIn(List<Integer> values) {
            addCriterion("zhiming_id not in", values, "zhimingId");
            return (Criteria) this;
        }

        public Criteria andZhimingIdBetween(Integer value1, Integer value2) {
            addCriterion("zhiming_id between", value1, value2, "zhimingId");
            return (Criteria) this;
        }

        public Criteria andZhimingIdNotBetween(Integer value1, Integer value2) {
            addCriterion("zhiming_id not between", value1, value2, "zhimingId");
            return (Criteria) this;
        }

        public Criteria andGangweiIdIsNull() {
            addCriterion("gangwei_id is null");
            return (Criteria) this;
        }

        public Criteria andGangweiIdIsNotNull() {
            addCriterion("gangwei_id is not null");
            return (Criteria) this;
        }

        public Criteria andGangweiIdEqualTo(Integer value) {
            addCriterion("gangwei_id =", value, "gangweiId");
            return (Criteria) this;
        }

        public Criteria andGangweiIdNotEqualTo(Integer value) {
            addCriterion("gangwei_id <>", value, "gangweiId");
            return (Criteria) this;
        }

        public Criteria andGangweiIdGreaterThan(Integer value) {
            addCriterion("gangwei_id >", value, "gangweiId");
            return (Criteria) this;
        }

        public Criteria andGangweiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("gangwei_id >=", value, "gangweiId");
            return (Criteria) this;
        }

        public Criteria andGangweiIdLessThan(Integer value) {
            addCriterion("gangwei_id <", value, "gangweiId");
            return (Criteria) this;
        }

        public Criteria andGangweiIdLessThanOrEqualTo(Integer value) {
            addCriterion("gangwei_id <=", value, "gangweiId");
            return (Criteria) this;
        }

        public Criteria andGangweiIdIn(List<Integer> values) {
            addCriterion("gangwei_id in", values, "gangweiId");
            return (Criteria) this;
        }

        public Criteria andGangweiIdNotIn(List<Integer> values) {
            addCriterion("gangwei_id not in", values, "gangweiId");
            return (Criteria) this;
        }

        public Criteria andGangweiIdBetween(Integer value1, Integer value2) {
            addCriterion("gangwei_id between", value1, value2, "gangweiId");
            return (Criteria) this;
        }

        public Criteria andGangweiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("gangwei_id not between", value1, value2, "gangweiId");
            return (Criteria) this;
        }

        public Criteria andBumenIdIsNull() {
            addCriterion("bumen_id is null");
            return (Criteria) this;
        }

        public Criteria andBumenIdIsNotNull() {
            addCriterion("bumen_id is not null");
            return (Criteria) this;
        }

        public Criteria andBumenIdEqualTo(Integer value) {
            addCriterion("bumen_id =", value, "bumenId");
            return (Criteria) this;
        }

        public Criteria andBumenIdNotEqualTo(Integer value) {
            addCriterion("bumen_id <>", value, "bumenId");
            return (Criteria) this;
        }

        public Criteria andBumenIdGreaterThan(Integer value) {
            addCriterion("bumen_id >", value, "bumenId");
            return (Criteria) this;
        }

        public Criteria andBumenIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bumen_id >=", value, "bumenId");
            return (Criteria) this;
        }

        public Criteria andBumenIdLessThan(Integer value) {
            addCriterion("bumen_id <", value, "bumenId");
            return (Criteria) this;
        }

        public Criteria andBumenIdLessThanOrEqualTo(Integer value) {
            addCriterion("bumen_id <=", value, "bumenId");
            return (Criteria) this;
        }

        public Criteria andBumenIdIn(List<Integer> values) {
            addCriterion("bumen_id in", values, "bumenId");
            return (Criteria) this;
        }

        public Criteria andBumenIdNotIn(List<Integer> values) {
            addCriterion("bumen_id not in", values, "bumenId");
            return (Criteria) this;
        }

        public Criteria andBumenIdBetween(Integer value1, Integer value2) {
            addCriterion("bumen_id between", value1, value2, "bumenId");
            return (Criteria) this;
        }

        public Criteria andBumenIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bumen_id not between", value1, value2, "bumenId");
            return (Criteria) this;
        }

        public Criteria andQuanxianIsNull() {
            addCriterion("quanxian is null");
            return (Criteria) this;
        }

        public Criteria andQuanxianIsNotNull() {
            addCriterion("quanxian is not null");
            return (Criteria) this;
        }

        public Criteria andQuanxianEqualTo(Integer value) {
            addCriterion("quanxian =", value, "quanxian");
            return (Criteria) this;
        }

        public Criteria andQuanxianNotEqualTo(Integer value) {
            addCriterion("quanxian <>", value, "quanxian");
            return (Criteria) this;
        }

        public Criteria andQuanxianGreaterThan(Integer value) {
            addCriterion("quanxian >", value, "quanxian");
            return (Criteria) this;
        }

        public Criteria andQuanxianGreaterThanOrEqualTo(Integer value) {
            addCriterion("quanxian >=", value, "quanxian");
            return (Criteria) this;
        }

        public Criteria andQuanxianLessThan(Integer value) {
            addCriterion("quanxian <", value, "quanxian");
            return (Criteria) this;
        }

        public Criteria andQuanxianLessThanOrEqualTo(Integer value) {
            addCriterion("quanxian <=", value, "quanxian");
            return (Criteria) this;
        }

        public Criteria andQuanxianIn(List<Integer> values) {
            addCriterion("quanxian in", values, "quanxian");
            return (Criteria) this;
        }

        public Criteria andQuanxianNotIn(List<Integer> values) {
            addCriterion("quanxian not in", values, "quanxian");
            return (Criteria) this;
        }

        public Criteria andQuanxianBetween(Integer value1, Integer value2) {
            addCriterion("quanxian between", value1, value2, "quanxian");
            return (Criteria) this;
        }

        public Criteria andQuanxianNotBetween(Integer value1, Integer value2) {
            addCriterion("quanxian not between", value1, value2, "quanxian");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andShNumberIsNull() {
            addCriterion("sh_number is null");
            return (Criteria) this;
        }

        public Criteria andShNumberIsNotNull() {
            addCriterion("sh_number is not null");
            return (Criteria) this;
        }

        public Criteria andShNumberEqualTo(Integer value) {
            addCriterion("sh_number =", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberNotEqualTo(Integer value) {
            addCriterion("sh_number <>", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberGreaterThan(Integer value) {
            addCriterion("sh_number >", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("sh_number >=", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberLessThan(Integer value) {
            addCriterion("sh_number <", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberLessThanOrEqualTo(Integer value) {
            addCriterion("sh_number <=", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberIn(List<Integer> values) {
            addCriterion("sh_number in", values, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberNotIn(List<Integer> values) {
            addCriterion("sh_number not in", values, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberBetween(Integer value1, Integer value2) {
            addCriterion("sh_number between", value1, value2, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("sh_number not between", value1, value2, "shNumber");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUseZwIsNull() {
            addCriterion("use_zw is null");
            return (Criteria) this;
        }

        public Criteria andUseZwIsNotNull() {
            addCriterion("use_zw is not null");
            return (Criteria) this;
        }

        public Criteria andUseZwEqualTo(String value) {
            addCriterion("use_zw =", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwNotEqualTo(String value) {
            addCriterion("use_zw <>", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwGreaterThan(String value) {
            addCriterion("use_zw >", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwGreaterThanOrEqualTo(String value) {
            addCriterion("use_zw >=", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwLessThan(String value) {
            addCriterion("use_zw <", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwLessThanOrEqualTo(String value) {
            addCriterion("use_zw <=", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwLike(String value) {
            addCriterion("use_zw like", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwNotLike(String value) {
            addCriterion("use_zw not like", value, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwIn(List<String> values) {
            addCriterion("use_zw in", values, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwNotIn(List<String> values) {
            addCriterion("use_zw not in", values, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwBetween(String value1, String value2) {
            addCriterion("use_zw between", value1, value2, "useZw");
            return (Criteria) this;
        }

        public Criteria andUseZwNotBetween(String value1, String value2) {
            addCriterion("use_zw not between", value1, value2, "useZw");
            return (Criteria) this;
        }

        public Criteria andUserBak1IsNull() {
            addCriterion("user_bak1 is null");
            return (Criteria) this;
        }

        public Criteria andUserBak1IsNotNull() {
            addCriterion("user_bak1 is not null");
            return (Criteria) this;
        }

        public Criteria andUserBak1EqualTo(String value) {
            addCriterion("user_bak1 =", value, "userBak1");
            return (Criteria) this;
        }

        public Criteria andUserBak1NotEqualTo(String value) {
            addCriterion("user_bak1 <>", value, "userBak1");
            return (Criteria) this;
        }

        public Criteria andUserBak1GreaterThan(String value) {
            addCriterion("user_bak1 >", value, "userBak1");
            return (Criteria) this;
        }

        public Criteria andUserBak1GreaterThanOrEqualTo(String value) {
            addCriterion("user_bak1 >=", value, "userBak1");
            return (Criteria) this;
        }

        public Criteria andUserBak1LessThan(String value) {
            addCriterion("user_bak1 <", value, "userBak1");
            return (Criteria) this;
        }

        public Criteria andUserBak1LessThanOrEqualTo(String value) {
            addCriterion("user_bak1 <=", value, "userBak1");
            return (Criteria) this;
        }

        public Criteria andUserBak1Like(String value) {
            addCriterion("user_bak1 like", value, "userBak1");
            return (Criteria) this;
        }

        public Criteria andUserBak1NotLike(String value) {
            addCriterion("user_bak1 not like", value, "userBak1");
            return (Criteria) this;
        }

        public Criteria andUserBak1In(List<String> values) {
            addCriterion("user_bak1 in", values, "userBak1");
            return (Criteria) this;
        }

        public Criteria andUserBak1NotIn(List<String> values) {
            addCriterion("user_bak1 not in", values, "userBak1");
            return (Criteria) this;
        }

        public Criteria andUserBak1Between(String value1, String value2) {
            addCriterion("user_bak1 between", value1, value2, "userBak1");
            return (Criteria) this;
        }

        public Criteria andUserBak1NotBetween(String value1, String value2) {
            addCriterion("user_bak1 not between", value1, value2, "userBak1");
            return (Criteria) this;
        }

        public Criteria andUserBak2IsNull() {
            addCriterion("user_bak2 is null");
            return (Criteria) this;
        }

        public Criteria andUserBak2IsNotNull() {
            addCriterion("user_bak2 is not null");
            return (Criteria) this;
        }

        public Criteria andUserBak2EqualTo(String value) {
            addCriterion("user_bak2 =", value, "userBak2");
            return (Criteria) this;
        }

        public Criteria andUserBak2NotEqualTo(String value) {
            addCriterion("user_bak2 <>", value, "userBak2");
            return (Criteria) this;
        }

        public Criteria andUserBak2GreaterThan(String value) {
            addCriterion("user_bak2 >", value, "userBak2");
            return (Criteria) this;
        }

        public Criteria andUserBak2GreaterThanOrEqualTo(String value) {
            addCriterion("user_bak2 >=", value, "userBak2");
            return (Criteria) this;
        }

        public Criteria andUserBak2LessThan(String value) {
            addCriterion("user_bak2 <", value, "userBak2");
            return (Criteria) this;
        }

        public Criteria andUserBak2LessThanOrEqualTo(String value) {
            addCriterion("user_bak2 <=", value, "userBak2");
            return (Criteria) this;
        }

        public Criteria andUserBak2Like(String value) {
            addCriterion("user_bak2 like", value, "userBak2");
            return (Criteria) this;
        }

        public Criteria andUserBak2NotLike(String value) {
            addCriterion("user_bak2 not like", value, "userBak2");
            return (Criteria) this;
        }

        public Criteria andUserBak2In(List<String> values) {
            addCriterion("user_bak2 in", values, "userBak2");
            return (Criteria) this;
        }

        public Criteria andUserBak2NotIn(List<String> values) {
            addCriterion("user_bak2 not in", values, "userBak2");
            return (Criteria) this;
        }

        public Criteria andUserBak2Between(String value1, String value2) {
            addCriterion("user_bak2 between", value1, value2, "userBak2");
            return (Criteria) this;
        }

        public Criteria andUserBak2NotBetween(String value1, String value2) {
            addCriterion("user_bak2 not between", value1, value2, "userBak2");
            return (Criteria) this;
        }

        public Criteria andUserBak3IsNull() {
            addCriterion("user_bak3 is null");
            return (Criteria) this;
        }

        public Criteria andUserBak3IsNotNull() {
            addCriterion("user_bak3 is not null");
            return (Criteria) this;
        }

        public Criteria andUserBak3EqualTo(String value) {
            addCriterion("user_bak3 =", value, "userBak3");
            return (Criteria) this;
        }

        public Criteria andUserBak3NotEqualTo(String value) {
            addCriterion("user_bak3 <>", value, "userBak3");
            return (Criteria) this;
        }

        public Criteria andUserBak3GreaterThan(String value) {
            addCriterion("user_bak3 >", value, "userBak3");
            return (Criteria) this;
        }

        public Criteria andUserBak3GreaterThanOrEqualTo(String value) {
            addCriterion("user_bak3 >=", value, "userBak3");
            return (Criteria) this;
        }

        public Criteria andUserBak3LessThan(String value) {
            addCriterion("user_bak3 <", value, "userBak3");
            return (Criteria) this;
        }

        public Criteria andUserBak3LessThanOrEqualTo(String value) {
            addCriterion("user_bak3 <=", value, "userBak3");
            return (Criteria) this;
        }

        public Criteria andUserBak3Like(String value) {
            addCriterion("user_bak3 like", value, "userBak3");
            return (Criteria) this;
        }

        public Criteria andUserBak3NotLike(String value) {
            addCriterion("user_bak3 not like", value, "userBak3");
            return (Criteria) this;
        }

        public Criteria andUserBak3In(List<String> values) {
            addCriterion("user_bak3 in", values, "userBak3");
            return (Criteria) this;
        }

        public Criteria andUserBak3NotIn(List<String> values) {
            addCriterion("user_bak3 not in", values, "userBak3");
            return (Criteria) this;
        }

        public Criteria andUserBak3Between(String value1, String value2) {
            addCriterion("user_bak3 between", value1, value2, "userBak3");
            return (Criteria) this;
        }

        public Criteria andUserBak3NotBetween(String value1, String value2) {
            addCriterion("user_bak3 not between", value1, value2, "userBak3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cbhs_user
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}