package com.sc.dmh.beans;

import java.io.Serializable;

public class CbhsUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cbhs_user.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cbhs_user.user_xm
     *
     * @mbggenerated
     */
    private String userXm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cbhs_user.zhiming_id
     *
     * @mbggenerated
     */
    private Integer zhimingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cbhs_user.gangwei_id
     *
     * @mbggenerated
     */
    private Integer gangweiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cbhs_user.bumen_id
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cbhs_user.quanxian
     *
     * @mbggenerated
     */
    private Integer quanxian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cbhs_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cbhs_user.sh_number
     *
     * @mbggenerated
     */
    private Integer shNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cbhs_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cbhs_user.use_zw
     *
     * @mbggenerated
     */
    private String useZw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cbhs_user.user_bak1
     *
     * @mbggenerated
     */
    private String userBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cbhs_user.user_bak2
     *
     * @mbggenerated
     */
    private String userBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cbhs_user.user_bak3
     *
     * @mbggenerated
     */
    private String userBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cbhs_user.user_id
     *
     * @return the value of cbhs_user.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cbhs_user.user_id
     *
     * @param userId the value for cbhs_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cbhs_user.user_xm
     *
     * @return the value of cbhs_user.user_xm
     *
     * @mbggenerated
     */
    public String getUserXm() {
        return userXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cbhs_user.user_xm
     *
     * @param userXm the value for cbhs_user.user_xm
     *
     * @mbggenerated
     */
    public void setUserXm(String userXm) {
        this.userXm = userXm == null ? null : userXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cbhs_user.zhiming_id
     *
     * @return the value of cbhs_user.zhiming_id
     *
     * @mbggenerated
     */
    public Integer getZhimingId() {
        return zhimingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cbhs_user.zhiming_id
     *
     * @param zhimingId the value for cbhs_user.zhiming_id
     *
     * @mbggenerated
     */
    public void setZhimingId(Integer zhimingId) {
        this.zhimingId = zhimingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cbhs_user.gangwei_id
     *
     * @return the value of cbhs_user.gangwei_id
     *
     * @mbggenerated
     */
    public Integer getGangweiId() {
        return gangweiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cbhs_user.gangwei_id
     *
     * @param gangweiId the value for cbhs_user.gangwei_id
     *
     * @mbggenerated
     */
    public void setGangweiId(Integer gangweiId) {
        this.gangweiId = gangweiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cbhs_user.bumen_id
     *
     * @return the value of cbhs_user.bumen_id
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cbhs_user.bumen_id
     *
     * @param bumenId the value for cbhs_user.bumen_id
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cbhs_user.quanxian
     *
     * @return the value of cbhs_user.quanxian
     *
     * @mbggenerated
     */
    public Integer getQuanxian() {
        return quanxian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cbhs_user.quanxian
     *
     * @param quanxian the value for cbhs_user.quanxian
     *
     * @mbggenerated
     */
    public void setQuanxian(Integer quanxian) {
        this.quanxian = quanxian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cbhs_user.password
     *
     * @return the value of cbhs_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cbhs_user.password
     *
     * @param password the value for cbhs_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cbhs_user.sh_number
     *
     * @return the value of cbhs_user.sh_number
     *
     * @mbggenerated
     */
    public Integer getShNumber() {
        return shNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cbhs_user.sh_number
     *
     * @param shNumber the value for cbhs_user.sh_number
     *
     * @mbggenerated
     */
    public void setShNumber(Integer shNumber) {
        this.shNumber = shNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cbhs_user.user_name
     *
     * @return the value of cbhs_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cbhs_user.user_name
     *
     * @param userName the value for cbhs_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cbhs_user.use_zw
     *
     * @return the value of cbhs_user.use_zw
     *
     * @mbggenerated
     */
    public String getUseZw() {
        return useZw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cbhs_user.use_zw
     *
     * @param useZw the value for cbhs_user.use_zw
     *
     * @mbggenerated
     */
    public void setUseZw(String useZw) {
        this.useZw = useZw == null ? null : useZw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cbhs_user.user_bak1
     *
     * @return the value of cbhs_user.user_bak1
     *
     * @mbggenerated
     */
    public String getUserBak1() {
        return userBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cbhs_user.user_bak1
     *
     * @param userBak1 the value for cbhs_user.user_bak1
     *
     * @mbggenerated
     */
    public void setUserBak1(String userBak1) {
        this.userBak1 = userBak1 == null ? null : userBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cbhs_user.user_bak2
     *
     * @return the value of cbhs_user.user_bak2
     *
     * @mbggenerated
     */
    public String getUserBak2() {
        return userBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cbhs_user.user_bak2
     *
     * @param userBak2 the value for cbhs_user.user_bak2
     *
     * @mbggenerated
     */
    public void setUserBak2(String userBak2) {
        this.userBak2 = userBak2 == null ? null : userBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cbhs_user.user_bak3
     *
     * @return the value of cbhs_user.user_bak3
     *
     * @mbggenerated
     */
    public String getUserBak3() {
        return userBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cbhs_user.user_bak3
     *
     * @param userBak3 the value for cbhs_user.user_bak3
     *
     * @mbggenerated
     */
    public void setUserBak3(String userBak3) {
        this.userBak3 = userBak3 == null ? null : userBak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CbhsUser other = (CbhsUser) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserXm() == null ? other.getUserXm() == null : this.getUserXm().equals(other.getUserXm()))
            && (this.getZhimingId() == null ? other.getZhimingId() == null : this.getZhimingId().equals(other.getZhimingId()))
            && (this.getGangweiId() == null ? other.getGangweiId() == null : this.getGangweiId().equals(other.getGangweiId()))
            && (this.getBumenId() == null ? other.getBumenId() == null : this.getBumenId().equals(other.getBumenId()))
            && (this.getQuanxian() == null ? other.getQuanxian() == null : this.getQuanxian().equals(other.getQuanxian()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getShNumber() == null ? other.getShNumber() == null : this.getShNumber().equals(other.getShNumber()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getUseZw() == null ? other.getUseZw() == null : this.getUseZw().equals(other.getUseZw()))
            && (this.getUserBak1() == null ? other.getUserBak1() == null : this.getUserBak1().equals(other.getUserBak1()))
            && (this.getUserBak2() == null ? other.getUserBak2() == null : this.getUserBak2().equals(other.getUserBak2()))
            && (this.getUserBak3() == null ? other.getUserBak3() == null : this.getUserBak3().equals(other.getUserBak3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserXm() == null) ? 0 : getUserXm().hashCode());
        result = prime * result + ((getZhimingId() == null) ? 0 : getZhimingId().hashCode());
        result = prime * result + ((getGangweiId() == null) ? 0 : getGangweiId().hashCode());
        result = prime * result + ((getBumenId() == null) ? 0 : getBumenId().hashCode());
        result = prime * result + ((getQuanxian() == null) ? 0 : getQuanxian().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getShNumber() == null) ? 0 : getShNumber().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getUseZw() == null) ? 0 : getUseZw().hashCode());
        result = prime * result + ((getUserBak1() == null) ? 0 : getUserBak1().hashCode());
        result = prime * result + ((getUserBak2() == null) ? 0 : getUserBak2().hashCode());
        result = prime * result + ((getUserBak3() == null) ? 0 : getUserBak3().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cbhs_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userXm=").append(userXm);
        sb.append(", zhimingId=").append(zhimingId);
        sb.append(", gangweiId=").append(gangweiId);
        sb.append(", bumenId=").append(bumenId);
        sb.append(", quanxian=").append(quanxian);
        sb.append(", password=").append(password);
        sb.append(", shNumber=").append(shNumber);
        sb.append(", userName=").append(userName);
        sb.append(", useZw=").append(useZw);
        sb.append(", userBak1=").append(userBak1);
        sb.append(", userBak2=").append(userBak2);
        sb.append(", userBak3=").append(userBak3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}