package com.sc.dmh.beans;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SignExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sign
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sign
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sign
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    public SignExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sign
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andPlaceIdIsNull() {
            addCriterion("place_id is null");
            return (Criteria) this;
        }

        public Criteria andPlaceIdIsNotNull() {
            addCriterion("place_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceIdEqualTo(Integer value) {
            addCriterion("place_id =", value, "placeId");
            return (Criteria) this;
        }

        public Criteria andPlaceIdNotEqualTo(Integer value) {
            addCriterion("place_id <>", value, "placeId");
            return (Criteria) this;
        }

        public Criteria andPlaceIdGreaterThan(Integer value) {
            addCriterion("place_id >", value, "placeId");
            return (Criteria) this;
        }

        public Criteria andPlaceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("place_id >=", value, "placeId");
            return (Criteria) this;
        }

        public Criteria andPlaceIdLessThan(Integer value) {
            addCriterion("place_id <", value, "placeId");
            return (Criteria) this;
        }

        public Criteria andPlaceIdLessThanOrEqualTo(Integer value) {
            addCriterion("place_id <=", value, "placeId");
            return (Criteria) this;
        }

        public Criteria andPlaceIdIn(List<Integer> values) {
            addCriterion("place_id in", values, "placeId");
            return (Criteria) this;
        }

        public Criteria andPlaceIdNotIn(List<Integer> values) {
            addCriterion("place_id not in", values, "placeId");
            return (Criteria) this;
        }

        public Criteria andPlaceIdBetween(Integer value1, Integer value2) {
            addCriterion("place_id between", value1, value2, "placeId");
            return (Criteria) this;
        }

        public Criteria andPlaceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("place_id not between", value1, value2, "placeId");
            return (Criteria) this;
        }

        public Criteria andSignIntimeIsNull() {
            addCriterion("sign_intime is null");
            return (Criteria) this;
        }

        public Criteria andSignIntimeIsNotNull() {
            addCriterion("sign_intime is not null");
            return (Criteria) this;
        }

        public Criteria andSignIntimeEqualTo(Date value) {
            addCriterion("sign_intime =", value, "signIntime");
            return (Criteria) this;
        }

        public Criteria andSignIntimeNotEqualTo(Date value) {
            addCriterion("sign_intime <>", value, "signIntime");
            return (Criteria) this;
        }

        public Criteria andSignIntimeGreaterThan(Date value) {
            addCriterion("sign_intime >", value, "signIntime");
            return (Criteria) this;
        }

        public Criteria andSignIntimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sign_intime >=", value, "signIntime");
            return (Criteria) this;
        }

        public Criteria andSignIntimeLessThan(Date value) {
            addCriterion("sign_intime <", value, "signIntime");
            return (Criteria) this;
        }

        public Criteria andSignIntimeLessThanOrEqualTo(Date value) {
            addCriterion("sign_intime <=", value, "signIntime");
            return (Criteria) this;
        }

        public Criteria andSignIntimeIn(List<Date> values) {
            addCriterion("sign_intime in", values, "signIntime");
            return (Criteria) this;
        }

        public Criteria andSignIntimeNotIn(List<Date> values) {
            addCriterion("sign_intime not in", values, "signIntime");
            return (Criteria) this;
        }

        public Criteria andSignIntimeBetween(Date value1, Date value2) {
            addCriterion("sign_intime between", value1, value2, "signIntime");
            return (Criteria) this;
        }

        public Criteria andSignIntimeNotBetween(Date value1, Date value2) {
            addCriterion("sign_intime not between", value1, value2, "signIntime");
            return (Criteria) this;
        }

        public Criteria andSignOuttimeIsNull() {
            addCriterion("sign_outtime is null");
            return (Criteria) this;
        }

        public Criteria andSignOuttimeIsNotNull() {
            addCriterion("sign_outtime is not null");
            return (Criteria) this;
        }

        public Criteria andSignOuttimeEqualTo(Date value) {
            addCriterion("sign_outtime =", value, "signOuttime");
            return (Criteria) this;
        }

        public Criteria andSignOuttimeNotEqualTo(Date value) {
            addCriterion("sign_outtime <>", value, "signOuttime");
            return (Criteria) this;
        }

        public Criteria andSignOuttimeGreaterThan(Date value) {
            addCriterion("sign_outtime >", value, "signOuttime");
            return (Criteria) this;
        }

        public Criteria andSignOuttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sign_outtime >=", value, "signOuttime");
            return (Criteria) this;
        }

        public Criteria andSignOuttimeLessThan(Date value) {
            addCriterion("sign_outtime <", value, "signOuttime");
            return (Criteria) this;
        }

        public Criteria andSignOuttimeLessThanOrEqualTo(Date value) {
            addCriterion("sign_outtime <=", value, "signOuttime");
            return (Criteria) this;
        }

        public Criteria andSignOuttimeIn(List<Date> values) {
            addCriterion("sign_outtime in", values, "signOuttime");
            return (Criteria) this;
        }

        public Criteria andSignOuttimeNotIn(List<Date> values) {
            addCriterion("sign_outtime not in", values, "signOuttime");
            return (Criteria) this;
        }

        public Criteria andSignOuttimeBetween(Date value1, Date value2) {
            addCriterion("sign_outtime between", value1, value2, "signOuttime");
            return (Criteria) this;
        }

        public Criteria andSignOuttimeNotBetween(Date value1, Date value2) {
            addCriterion("sign_outtime not between", value1, value2, "signOuttime");
            return (Criteria) this;
        }

        public Criteria andSignInlatitudeIsNull() {
            addCriterion("sign_inlatitude is null");
            return (Criteria) this;
        }

        public Criteria andSignInlatitudeIsNotNull() {
            addCriterion("sign_inlatitude is not null");
            return (Criteria) this;
        }

        public Criteria andSignInlatitudeEqualTo(BigDecimal value) {
            addCriterion("sign_inlatitude =", value, "signInlatitude");
            return (Criteria) this;
        }

        public Criteria andSignInlatitudeNotEqualTo(BigDecimal value) {
            addCriterion("sign_inlatitude <>", value, "signInlatitude");
            return (Criteria) this;
        }

        public Criteria andSignInlatitudeGreaterThan(BigDecimal value) {
            addCriterion("sign_inlatitude >", value, "signInlatitude");
            return (Criteria) this;
        }

        public Criteria andSignInlatitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sign_inlatitude >=", value, "signInlatitude");
            return (Criteria) this;
        }

        public Criteria andSignInlatitudeLessThan(BigDecimal value) {
            addCriterion("sign_inlatitude <", value, "signInlatitude");
            return (Criteria) this;
        }

        public Criteria andSignInlatitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sign_inlatitude <=", value, "signInlatitude");
            return (Criteria) this;
        }

        public Criteria andSignInlatitudeIn(List<BigDecimal> values) {
            addCriterion("sign_inlatitude in", values, "signInlatitude");
            return (Criteria) this;
        }

        public Criteria andSignInlatitudeNotIn(List<BigDecimal> values) {
            addCriterion("sign_inlatitude not in", values, "signInlatitude");
            return (Criteria) this;
        }

        public Criteria andSignInlatitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sign_inlatitude between", value1, value2, "signInlatitude");
            return (Criteria) this;
        }

        public Criteria andSignInlatitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sign_inlatitude not between", value1, value2, "signInlatitude");
            return (Criteria) this;
        }

        public Criteria andSignInlongitudeIsNull() {
            addCriterion("sign_inlongitude is null");
            return (Criteria) this;
        }

        public Criteria andSignInlongitudeIsNotNull() {
            addCriterion("sign_inlongitude is not null");
            return (Criteria) this;
        }

        public Criteria andSignInlongitudeEqualTo(BigDecimal value) {
            addCriterion("sign_inlongitude =", value, "signInlongitude");
            return (Criteria) this;
        }

        public Criteria andSignInlongitudeNotEqualTo(BigDecimal value) {
            addCriterion("sign_inlongitude <>", value, "signInlongitude");
            return (Criteria) this;
        }

        public Criteria andSignInlongitudeGreaterThan(BigDecimal value) {
            addCriterion("sign_inlongitude >", value, "signInlongitude");
            return (Criteria) this;
        }

        public Criteria andSignInlongitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sign_inlongitude >=", value, "signInlongitude");
            return (Criteria) this;
        }

        public Criteria andSignInlongitudeLessThan(BigDecimal value) {
            addCriterion("sign_inlongitude <", value, "signInlongitude");
            return (Criteria) this;
        }

        public Criteria andSignInlongitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sign_inlongitude <=", value, "signInlongitude");
            return (Criteria) this;
        }

        public Criteria andSignInlongitudeIn(List<BigDecimal> values) {
            addCriterion("sign_inlongitude in", values, "signInlongitude");
            return (Criteria) this;
        }

        public Criteria andSignInlongitudeNotIn(List<BigDecimal> values) {
            addCriterion("sign_inlongitude not in", values, "signInlongitude");
            return (Criteria) this;
        }

        public Criteria andSignInlongitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sign_inlongitude between", value1, value2, "signInlongitude");
            return (Criteria) this;
        }

        public Criteria andSignInlongitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sign_inlongitude not between", value1, value2, "signInlongitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlatitudeIsNull() {
            addCriterion("sign_outlatitude is null");
            return (Criteria) this;
        }

        public Criteria andSignOutlatitudeIsNotNull() {
            addCriterion("sign_outlatitude is not null");
            return (Criteria) this;
        }

        public Criteria andSignOutlatitudeEqualTo(BigDecimal value) {
            addCriterion("sign_outlatitude =", value, "signOutlatitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlatitudeNotEqualTo(BigDecimal value) {
            addCriterion("sign_outlatitude <>", value, "signOutlatitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlatitudeGreaterThan(BigDecimal value) {
            addCriterion("sign_outlatitude >", value, "signOutlatitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlatitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sign_outlatitude >=", value, "signOutlatitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlatitudeLessThan(BigDecimal value) {
            addCriterion("sign_outlatitude <", value, "signOutlatitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlatitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sign_outlatitude <=", value, "signOutlatitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlatitudeIn(List<BigDecimal> values) {
            addCriterion("sign_outlatitude in", values, "signOutlatitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlatitudeNotIn(List<BigDecimal> values) {
            addCriterion("sign_outlatitude not in", values, "signOutlatitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlatitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sign_outlatitude between", value1, value2, "signOutlatitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlatitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sign_outlatitude not between", value1, value2, "signOutlatitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlongitudeIsNull() {
            addCriterion("sign_outlongitude is null");
            return (Criteria) this;
        }

        public Criteria andSignOutlongitudeIsNotNull() {
            addCriterion("sign_outlongitude is not null");
            return (Criteria) this;
        }

        public Criteria andSignOutlongitudeEqualTo(BigDecimal value) {
            addCriterion("sign_outlongitude =", value, "signOutlongitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlongitudeNotEqualTo(BigDecimal value) {
            addCriterion("sign_outlongitude <>", value, "signOutlongitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlongitudeGreaterThan(BigDecimal value) {
            addCriterion("sign_outlongitude >", value, "signOutlongitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlongitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sign_outlongitude >=", value, "signOutlongitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlongitudeLessThan(BigDecimal value) {
            addCriterion("sign_outlongitude <", value, "signOutlongitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlongitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sign_outlongitude <=", value, "signOutlongitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlongitudeIn(List<BigDecimal> values) {
            addCriterion("sign_outlongitude in", values, "signOutlongitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlongitudeNotIn(List<BigDecimal> values) {
            addCriterion("sign_outlongitude not in", values, "signOutlongitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlongitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sign_outlongitude between", value1, value2, "signOutlongitude");
            return (Criteria) this;
        }

        public Criteria andSignOutlongitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sign_outlongitude not between", value1, value2, "signOutlongitude");
            return (Criteria) this;
        }

        public Criteria andSignStateIsNull() {
            addCriterion("sign_state is null");
            return (Criteria) this;
        }

        public Criteria andSignStateIsNotNull() {
            addCriterion("sign_state is not null");
            return (Criteria) this;
        }

        public Criteria andSignStateEqualTo(Integer value) {
            addCriterion("sign_state =", value, "signState");
            return (Criteria) this;
        }

        public Criteria andSignStateNotEqualTo(Integer value) {
            addCriterion("sign_state <>", value, "signState");
            return (Criteria) this;
        }

        public Criteria andSignStateGreaterThan(Integer value) {
            addCriterion("sign_state >", value, "signState");
            return (Criteria) this;
        }

        public Criteria andSignStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("sign_state >=", value, "signState");
            return (Criteria) this;
        }

        public Criteria andSignStateLessThan(Integer value) {
            addCriterion("sign_state <", value, "signState");
            return (Criteria) this;
        }

        public Criteria andSignStateLessThanOrEqualTo(Integer value) {
            addCriterion("sign_state <=", value, "signState");
            return (Criteria) this;
        }

        public Criteria andSignStateIn(List<Integer> values) {
            addCriterion("sign_state in", values, "signState");
            return (Criteria) this;
        }

        public Criteria andSignStateNotIn(List<Integer> values) {
            addCriterion("sign_state not in", values, "signState");
            return (Criteria) this;
        }

        public Criteria andSignStateBetween(Integer value1, Integer value2) {
            addCriterion("sign_state between", value1, value2, "signState");
            return (Criteria) this;
        }

        public Criteria andSignStateNotBetween(Integer value1, Integer value2) {
            addCriterion("sign_state not between", value1, value2, "signState");
            return (Criteria) this;
        }

        public Criteria andSignBack1IsNull() {
            addCriterion("sign_back1 is null");
            return (Criteria) this;
        }

        public Criteria andSignBack1IsNotNull() {
            addCriterion("sign_back1 is not null");
            return (Criteria) this;
        }

        public Criteria andSignBack1EqualTo(String value) {
            addCriterion("sign_back1 =", value, "signBack1");
            return (Criteria) this;
        }

        public Criteria andSignBack1NotEqualTo(String value) {
            addCriterion("sign_back1 <>", value, "signBack1");
            return (Criteria) this;
        }

        public Criteria andSignBack1GreaterThan(String value) {
            addCriterion("sign_back1 >", value, "signBack1");
            return (Criteria) this;
        }

        public Criteria andSignBack1GreaterThanOrEqualTo(String value) {
            addCriterion("sign_back1 >=", value, "signBack1");
            return (Criteria) this;
        }

        public Criteria andSignBack1LessThan(String value) {
            addCriterion("sign_back1 <", value, "signBack1");
            return (Criteria) this;
        }

        public Criteria andSignBack1LessThanOrEqualTo(String value) {
            addCriterion("sign_back1 <=", value, "signBack1");
            return (Criteria) this;
        }

        public Criteria andSignBack1Like(String value) {
            addCriterion("sign_back1 like", value, "signBack1");
            return (Criteria) this;
        }

        public Criteria andSignBack1NotLike(String value) {
            addCriterion("sign_back1 not like", value, "signBack1");
            return (Criteria) this;
        }

        public Criteria andSignBack1In(List<String> values) {
            addCriterion("sign_back1 in", values, "signBack1");
            return (Criteria) this;
        }

        public Criteria andSignBack1NotIn(List<String> values) {
            addCriterion("sign_back1 not in", values, "signBack1");
            return (Criteria) this;
        }

        public Criteria andSignBack1Between(String value1, String value2) {
            addCriterion("sign_back1 between", value1, value2, "signBack1");
            return (Criteria) this;
        }

        public Criteria andSignBack1NotBetween(String value1, String value2) {
            addCriterion("sign_back1 not between", value1, value2, "signBack1");
            return (Criteria) this;
        }

        public Criteria andSignBack2IsNull() {
            addCriterion("sign_back2 is null");
            return (Criteria) this;
        }

        public Criteria andSignBack2IsNotNull() {
            addCriterion("sign_back2 is not null");
            return (Criteria) this;
        }

        public Criteria andSignBack2EqualTo(String value) {
            addCriterion("sign_back2 =", value, "signBack2");
            return (Criteria) this;
        }

        public Criteria andSignBack2NotEqualTo(String value) {
            addCriterion("sign_back2 <>", value, "signBack2");
            return (Criteria) this;
        }

        public Criteria andSignBack2GreaterThan(String value) {
            addCriterion("sign_back2 >", value, "signBack2");
            return (Criteria) this;
        }

        public Criteria andSignBack2GreaterThanOrEqualTo(String value) {
            addCriterion("sign_back2 >=", value, "signBack2");
            return (Criteria) this;
        }

        public Criteria andSignBack2LessThan(String value) {
            addCriterion("sign_back2 <", value, "signBack2");
            return (Criteria) this;
        }

        public Criteria andSignBack2LessThanOrEqualTo(String value) {
            addCriterion("sign_back2 <=", value, "signBack2");
            return (Criteria) this;
        }

        public Criteria andSignBack2Like(String value) {
            addCriterion("sign_back2 like", value, "signBack2");
            return (Criteria) this;
        }

        public Criteria andSignBack2NotLike(String value) {
            addCriterion("sign_back2 not like", value, "signBack2");
            return (Criteria) this;
        }

        public Criteria andSignBack2In(List<String> values) {
            addCriterion("sign_back2 in", values, "signBack2");
            return (Criteria) this;
        }

        public Criteria andSignBack2NotIn(List<String> values) {
            addCriterion("sign_back2 not in", values, "signBack2");
            return (Criteria) this;
        }

        public Criteria andSignBack2Between(String value1, String value2) {
            addCriterion("sign_back2 between", value1, value2, "signBack2");
            return (Criteria) this;
        }

        public Criteria andSignBack2NotBetween(String value1, String value2) {
            addCriterion("sign_back2 not between", value1, value2, "signBack2");
            return (Criteria) this;
        }

        public Criteria andSignBack3IsNull() {
            addCriterion("sign_back3 is null");
            return (Criteria) this;
        }

        public Criteria andSignBack3IsNotNull() {
            addCriterion("sign_back3 is not null");
            return (Criteria) this;
        }

        public Criteria andSignBack3EqualTo(String value) {
            addCriterion("sign_back3 =", value, "signBack3");
            return (Criteria) this;
        }

        public Criteria andSignBack3NotEqualTo(String value) {
            addCriterion("sign_back3 <>", value, "signBack3");
            return (Criteria) this;
        }

        public Criteria andSignBack3GreaterThan(String value) {
            addCriterion("sign_back3 >", value, "signBack3");
            return (Criteria) this;
        }

        public Criteria andSignBack3GreaterThanOrEqualTo(String value) {
            addCriterion("sign_back3 >=", value, "signBack3");
            return (Criteria) this;
        }

        public Criteria andSignBack3LessThan(String value) {
            addCriterion("sign_back3 <", value, "signBack3");
            return (Criteria) this;
        }

        public Criteria andSignBack3LessThanOrEqualTo(String value) {
            addCriterion("sign_back3 <=", value, "signBack3");
            return (Criteria) this;
        }

        public Criteria andSignBack3Like(String value) {
            addCriterion("sign_back3 like", value, "signBack3");
            return (Criteria) this;
        }

        public Criteria andSignBack3NotLike(String value) {
            addCriterion("sign_back3 not like", value, "signBack3");
            return (Criteria) this;
        }

        public Criteria andSignBack3In(List<String> values) {
            addCriterion("sign_back3 in", values, "signBack3");
            return (Criteria) this;
        }

        public Criteria andSignBack3NotIn(List<String> values) {
            addCriterion("sign_back3 not in", values, "signBack3");
            return (Criteria) this;
        }

        public Criteria andSignBack3Between(String value1, String value2) {
            addCriterion("sign_back3 between", value1, value2, "signBack3");
            return (Criteria) this;
        }

        public Criteria andSignBack3NotBetween(String value1, String value2) {
            addCriterion("sign_back3 not between", value1, value2, "signBack3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sign
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sign
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}