package com.sc.dmh.beans;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Sign implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.place_id
     *
     * @mbggenerated
     */
    private Integer placeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_intime
     *
     * @mbggenerated
     */
    private Date signIntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_outtime
     *
     * @mbggenerated
     */
    private Date signOuttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_inlatitude
     *
     * @mbggenerated
     */
    private BigDecimal signInlatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_inlongitude
     *
     * @mbggenerated
     */
    private BigDecimal signInlongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_outlatitude
     *
     * @mbggenerated
     */
    private BigDecimal signOutlatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_outlongitude
     *
     * @mbggenerated
     */
    private BigDecimal signOutlongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_state
     *
     * @mbggenerated
     */
    private Integer signState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_back1
     *
     * @mbggenerated
     */
    private String signBack1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_back2
     *
     * @mbggenerated
     */
    private String signBack2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_back3
     *
     * @mbggenerated
     */
    private String signBack3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sign
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.id
     *
     * @return the value of sign.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.id
     *
     * @param id the value for sign.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.user_id
     *
     * @return the value of sign.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.user_id
     *
     * @param userId the value for sign.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.place_id
     *
     * @return the value of sign.place_id
     *
     * @mbggenerated
     */
    public Integer getPlaceId() {
        return placeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.place_id
     *
     * @param placeId the value for sign.place_id
     *
     * @mbggenerated
     */
    public void setPlaceId(Integer placeId) {
        this.placeId = placeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_intime
     *
     * @return the value of sign.sign_intime
     *
     * @mbggenerated
     */
    public Date getSignIntime() {
        return signIntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_intime
     *
     * @param signIntime the value for sign.sign_intime
     *
     * @mbggenerated
     */
    public void setSignIntime(Date signIntime) {
        this.signIntime = signIntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_outtime
     *
     * @return the value of sign.sign_outtime
     *
     * @mbggenerated
     */
    public Date getSignOuttime() {
        return signOuttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_outtime
     *
     * @param signOuttime the value for sign.sign_outtime
     *
     * @mbggenerated
     */
    public void setSignOuttime(Date signOuttime) {
        this.signOuttime = signOuttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_inlatitude
     *
     * @return the value of sign.sign_inlatitude
     *
     * @mbggenerated
     */
    public BigDecimal getSignInlatitude() {
        return signInlatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_inlatitude
     *
     * @param signInlatitude the value for sign.sign_inlatitude
     *
     * @mbggenerated
     */
    public void setSignInlatitude(BigDecimal signInlatitude) {
        this.signInlatitude = signInlatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_inlongitude
     *
     * @return the value of sign.sign_inlongitude
     *
     * @mbggenerated
     */
    public BigDecimal getSignInlongitude() {
        return signInlongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_inlongitude
     *
     * @param signInlongitude the value for sign.sign_inlongitude
     *
     * @mbggenerated
     */
    public void setSignInlongitude(BigDecimal signInlongitude) {
        this.signInlongitude = signInlongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_outlatitude
     *
     * @return the value of sign.sign_outlatitude
     *
     * @mbggenerated
     */
    public BigDecimal getSignOutlatitude() {
        return signOutlatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_outlatitude
     *
     * @param signOutlatitude the value for sign.sign_outlatitude
     *
     * @mbggenerated
     */
    public void setSignOutlatitude(BigDecimal signOutlatitude) {
        this.signOutlatitude = signOutlatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_outlongitude
     *
     * @return the value of sign.sign_outlongitude
     *
     * @mbggenerated
     */
    public BigDecimal getSignOutlongitude() {
        return signOutlongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_outlongitude
     *
     * @param signOutlongitude the value for sign.sign_outlongitude
     *
     * @mbggenerated
     */
    public void setSignOutlongitude(BigDecimal signOutlongitude) {
        this.signOutlongitude = signOutlongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_state
     *
     * @return the value of sign.sign_state
     *
     * @mbggenerated
     */
    public Integer getSignState() {
        return signState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_state
     *
     * @param signState the value for sign.sign_state
     *
     * @mbggenerated
     */
    public void setSignState(Integer signState) {
        this.signState = signState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_back1
     *
     * @return the value of sign.sign_back1
     *
     * @mbggenerated
     */
    public String getSignBack1() {
        return signBack1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_back1
     *
     * @param signBack1 the value for sign.sign_back1
     *
     * @mbggenerated
     */
    public void setSignBack1(String signBack1) {
        this.signBack1 = signBack1 == null ? null : signBack1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_back2
     *
     * @return the value of sign.sign_back2
     *
     * @mbggenerated
     */
    public String getSignBack2() {
        return signBack2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_back2
     *
     * @param signBack2 the value for sign.sign_back2
     *
     * @mbggenerated
     */
    public void setSignBack2(String signBack2) {
        this.signBack2 = signBack2 == null ? null : signBack2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_back3
     *
     * @return the value of sign.sign_back3
     *
     * @mbggenerated
     */
    public String getSignBack3() {
        return signBack3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_back3
     *
     * @param signBack3 the value for sign.sign_back3
     *
     * @mbggenerated
     */
    public void setSignBack3(String signBack3) {
        this.signBack3 = signBack3 == null ? null : signBack3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Sign other = (Sign) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getPlaceId() == null ? other.getPlaceId() == null : this.getPlaceId().equals(other.getPlaceId()))
            && (this.getSignIntime() == null ? other.getSignIntime() == null : this.getSignIntime().equals(other.getSignIntime()))
            && (this.getSignOuttime() == null ? other.getSignOuttime() == null : this.getSignOuttime().equals(other.getSignOuttime()))
            && (this.getSignInlatitude() == null ? other.getSignInlatitude() == null : this.getSignInlatitude().equals(other.getSignInlatitude()))
            && (this.getSignInlongitude() == null ? other.getSignInlongitude() == null : this.getSignInlongitude().equals(other.getSignInlongitude()))
            && (this.getSignOutlatitude() == null ? other.getSignOutlatitude() == null : this.getSignOutlatitude().equals(other.getSignOutlatitude()))
            && (this.getSignOutlongitude() == null ? other.getSignOutlongitude() == null : this.getSignOutlongitude().equals(other.getSignOutlongitude()))
            && (this.getSignState() == null ? other.getSignState() == null : this.getSignState().equals(other.getSignState()))
            && (this.getSignBack1() == null ? other.getSignBack1() == null : this.getSignBack1().equals(other.getSignBack1()))
            && (this.getSignBack2() == null ? other.getSignBack2() == null : this.getSignBack2().equals(other.getSignBack2()))
            && (this.getSignBack3() == null ? other.getSignBack3() == null : this.getSignBack3().equals(other.getSignBack3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getPlaceId() == null) ? 0 : getPlaceId().hashCode());
        result = prime * result + ((getSignIntime() == null) ? 0 : getSignIntime().hashCode());
        result = prime * result + ((getSignOuttime() == null) ? 0 : getSignOuttime().hashCode());
        result = prime * result + ((getSignInlatitude() == null) ? 0 : getSignInlatitude().hashCode());
        result = prime * result + ((getSignInlongitude() == null) ? 0 : getSignInlongitude().hashCode());
        result = prime * result + ((getSignOutlatitude() == null) ? 0 : getSignOutlatitude().hashCode());
        result = prime * result + ((getSignOutlongitude() == null) ? 0 : getSignOutlongitude().hashCode());
        result = prime * result + ((getSignState() == null) ? 0 : getSignState().hashCode());
        result = prime * result + ((getSignBack1() == null) ? 0 : getSignBack1().hashCode());
        result = prime * result + ((getSignBack2() == null) ? 0 : getSignBack2().hashCode());
        result = prime * result + ((getSignBack3() == null) ? 0 : getSignBack3().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", placeId=").append(placeId);
        sb.append(", signIntime=").append(signIntime);
        sb.append(", signOuttime=").append(signOuttime);
        sb.append(", signInlatitude=").append(signInlatitude);
        sb.append(", signInlongitude=").append(signInlongitude);
        sb.append(", signOutlatitude=").append(signOutlatitude);
        sb.append(", signOutlongitude=").append(signOutlongitude);
        sb.append(", signState=").append(signState);
        sb.append(", signBack1=").append(signBack1);
        sb.append(", signBack2=").append(signBack2);
        sb.append(", signBack3=").append(signBack3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}