package com.sc.dmh.mapper;

import com.sc.dmh.beans.SignView;
import com.sc.dmh.beans.SignViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SignViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_view
     *
     * @mbggenerated
     */
    int countByExample(SignViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_view
     *
     * @mbggenerated
     */
    int deleteByExample(SignViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_view
     *
     * @mbggenerated
     */
    int insert(SignView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_view
     *
     * @mbggenerated
     */
    int insertSelective(SignView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_view
     *
     * @mbggenerated
     */
    List<SignView> selectByExample(SignViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_view
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SignView record, @Param("example") SignViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_view
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SignView record, @Param("example") SignViewExample example);
}